### ISSUE TITLE
ie8?

### ISSUE THREAD

**Issue by gpinkham** [williammalone/HTML5-Paint-Bucket-Tool#1]
hate creating issues for questions but no other way to do that on github (that I know of)..    Have you done any work on getting this to work with IE8?    I tried it with excanvas and it's a no go..

**Comment by williammalone** [comment]
It should work with iE8.  Are you running it locally or on a server?  There is a security issue that will limit accessing image data locally on most browsers.

**Comment by gpinkham** [comment]
yeah on a server..  works fine in everything but ie8..    in ie8 I get a blank white canvas. no duck..   I'll keep digging just wanted to check to see if you had any luck and if I missed something in your article/code..    thanks..

**Comment by williammalone** [comment]
I have confirmed the getImageData method does not work with IE8 even with ExplorerCanvas.
