### ISSUE TITLE
How to change picture image

### ISSUE THREAD

**Issue by isaacsf** [williammalone/HTML5-Paint-Bucket-Tool#2]
Hi,

First of all, congratulations for your excellent job with this tool.

A simple question: how can I replace the "watermelon" picture file to a bigger and different one?

Thank you in advance.

Isaac

**Comment by williammalone** [comment]
To change the outline image, change the <var>src</var> property of the <var>outlineImage</var> variable in the <var>init</var> function.  

Changing the dimensions of the drawing canvas is quite a bit more involved.  It includes changing the background image and drawing area variables.

**Comment by isaacsf** [comment]
Hello William,

Thank you for the answer.

I saw which variable had the source file, but the problem is about the new
image resolution (700x569px, in my case).

I'm playing with _drawingAreaX, drawingAreaY, drawingAreaWidth
*and_drawingAreaHeight
- variables, with no success at 100%.

My objective is to use my own color tools and layout, so I'm trying to have
the canvas object only with the drawing area inside (so the canvas will be
700x569px, same resolution like the image file).

Could help me on this?

Thank you in advance.

Regards,
