### ISSUE TITLE
Wrong click positions

### ISSUE THREAD

**Issue by viniciusbig** [williammalone/HTML5-Paint-Bucket-Tool#6]
in the createMouseEvents function we have

```
var mouseX = e.pageX - this.offsetLeft,
    mouseY = e.pageY - this.offsetTop;
```

but, with the canvasDiv inside another div structure, like bootstrap container, the click offset i not in the right place.

There is a way to fix it?
I couldn't figure out.

**Comment by williammalone** [comment]
I have fixed this in the past by using a function which recursively calculates the position each parent container.

See the `getElementPos` function in the controller of my game framework BlocksJS for the function I used: https://github.com/williammalone/BlocksJS/blob/master/src/js/controller.js

I don't have a specific example for the drawing app but the code would look something like this:

```
var elementPos = getElementPos(divElement);
var x = e.pageX - elementPos.x;
var y = e.pageY - elementPos.y;
```

  Let me know if you run into any issues.
